encoding: utf-8

# SEO相关信息
title: TMaize Blog
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2016 皖ICP备16016174号'

# 域名配置
# baseUrl配置,如果网站部署在根目录下的目录中，请设置为 /目录名
domainUrl: 'http://blog.tmaize.net'
baseUrl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 自定义插件,具体说明请看README文档
customPlugins:
  - use: true
    file: 'plugin-mta-stats.html'
    sid: 500581966
    cid: 500581972
  - use: true
    file: 'plugin-baidu-push.html'
  - use: true
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'build-tool']
