encoding: utf-8

# SEO相关信息
title: TMaize Blog
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2016 皖ICP备16016174号'

# 基础路径
baseUrl: ''

# 用来生成sitemap
# sitemapPrefix + baseUrl + post.url
sitemapPrefix: 'http://blog.tmaize.net'

## 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html
